services:
  postgres:
    restart: always
    env_file: .env.production
    # Tasca 2.2: Eliminem ports per fer la DB privada [cite: 20]
    ports: !reset []
    expose:
      - "5432"

  app-blue:
    restart: always
    env_file: .env.production
    build:
      context: .
      dockerfile: docker/app/Dockerfile

  app-green:
    restart: always
    env_file: .env.production
    build:
      context: .
      dockerfile: docker/app/Dockerfile

  nginx:
    restart: always
    ports:
      - "80:80" # Tasca 2.2: Únic punt d'entrada extern